### ISSUE TITLE
module 're' has no attribute

### ISSUE THREAD

**Issue by rbarrass** [ecriminal/phpvuln#2]
Hi, 
I installed requirements with pip and now I'm trying to launch phpvuln.py but I'm facing an error.

![image](https://user-images.githubusercontent.com/36269488/107523864-791b0a80-6bb5-11eb-8947-a2321cf29c71.png)

Please, somebody know how I can manage to resolve this issue ? 

Regards

**Comment by ecriminal** [comment]
What version of Python are you using?

Tbh, I might remove those type hints...

**Comment by rbarrass** [comment]
Hello and thank's for your help, I use Python 3.6.9

**Comment by rbarrass** [comment]
I upgrade my python version to 3.7.5 and now it's working

**Comment by ecriminal** [comment]
I'm glad you could fix it :)
